/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum150626;

import javax.swing.JOptionPane;

/**
 *
 * @author Night_kid
 */
public class FormPenilaian extends javax.swing.JFrame {

    /**
     * Creates new form FormPenilaian
     */
    public FormPenilaian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMatkul = new javax.swing.JLabel();
        lblTugas = new javax.swing.JLabel();
        lblquiz = new javax.swing.JLabel();
        lbluts = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtkelas = new javax.swing.JTextField();
        txtmatkul = new javax.swing.JTextField();
        txttugas = new javax.swing.JTextField();
        txtquiz = new javax.swing.JTextField();
        txtuts = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        txtNilaiAkhir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbluas = new javax.swing.JLabel();
        txtuas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblkonversi = new javax.swing.JLabel();
        txtkonversi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblJudul.setText("FORM PENILAIAAN MAHASISWA");

        lblNama.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNama.setText("Nama Mahasiswa");

        lblKelas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblKelas.setText("Kelas");

        lblMatkul.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMatkul.setText("MataKuliah");

        lblTugas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTugas.setText("Nilai Tugas");

        lblquiz.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblquiz.setText("Nilai Quiz");

        lbluts.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbluts.setText("Nilai UTS");

        txtuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtutsActionPerformed(evt);
            }
        });

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Nilai Akhir : ");

        lbluas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbluas.setText("Nilai UAS");

        lblkonversi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblkonversi.setText("Nilai Konversi : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(447, 447, 447))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama)
                    .addComponent(lblKelas)
                    .addComponent(lblMatkul)
                    .addComponent(lblTugas)
                    .addComponent(lblquiz)
                    .addComponent(lbluts)
                    .addComponent(lbluas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtuts, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtquiz, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttugas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnama)
                    .addComponent(txtkelas)
                    .addComponent(txtmatkul)
                    .addComponent(txtuas, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNilaiAkhir))
                    .addComponent(btnproses, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblkonversi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtkonversi)))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKelas)
                                    .addComponent(txtkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMatkul)
                                    .addComponent(txtmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnproses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTugas)
                            .addComponent(txttugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblquiz)
                                    .addComponent(txtquiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbluts)
                                    .addComponent(txtuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbluas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblkonversi)
                                    .addComponent(txtkonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(538, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtutsActionPerformed
        
    }//GEN-LAST:event_txtutsActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
       String nama = txtnama.getText();
        String kelas = txtkelas.getText();
        String matkul = txtmatkul.getText();
        
        if(nama.isEmpty()||kelas.isEmpty()||matkul.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua haeus diisi","Peringatan",JOptionPane.WARNING_MESSAGE);
            txtnama.setText("");
            txtnama.requestFocus();
        }
        
        if(txttugas.getText().isEmpty()||txtquiz.getText().isEmpty()||txtuts.getText().isEmpty()||txtuas.getText().isEmpty()){
            JOptionPane.showConfirmDialog(this,"Semua nilai harus diisi");
            }else{
            
   
        }
        try{
        double tugas = validasiNilai(txttugas.getText(),"Tugas");
        double quiz = validasiNilai(txtquiz.getText(),"quiz");
        double uts = validasiNilai(txtuts.getText(),"UTS");
        double uas = validasiNilai(txtuas.getText(),"UAS");
        
        double na = 0.15*tugas + 0.2*quiz + 0.3*uts + 0.35*uas;
        
        txtNilaiAkhir.setText(Double.toString(na));
        txtkonversi.setText(KonversiNilai(na));
        JOptionPane.showMessageDialog(this, "Nama : "+nama+
                "\nKelas : "+kelas+
                "\nMata Kuliah : "+matkul+
                "\nNilaiAKhir : "+na,
                "Hasil Penilaian",JOptionPane.INFORMATION_MESSAGE);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validasi Nilai",JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_btnprosesActionPerformed

    private double validasiNilai(String input, String jenisNilai) throws Exception{
        double nilai = Double.parseDouble(input);
        if(nilai<0 || nilai >100)
            throw new Exception (jenisNilai+ " harus antara 0 - 100");
        return nilai;
    }
    
   private String KonversiNilai(double nilai){
        if(nilai>=80)
            return "A";
        else if(nilai>=65)
            return "B";
        else if(nilai>=55)
            return "C";
        else if(nilai>=40)
            return "D";
        else
            return "E";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTugas;
    private javax.swing.JLabel lblkonversi;
    private javax.swing.JLabel lblquiz;
    private javax.swing.JLabel lbluas;
    private javax.swing.JLabel lbluts;
    private javax.swing.JTextField txtNilaiAkhir;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtkonversi;
    private javax.swing.JTextField txtmatkul;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtquiz;
    private javax.swing.JTextField txttugas;
    private javax.swing.JTextField txtuas;
    private javax.swing.JTextField txtuts;
    // End of variables declaration//GEN-END:variables
}
