/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum220626;

import javax.swing.JOptionPane;

/**
 *
 * @author Night_kid
 */
public class FormGajiPegawai extends javax.swing.JFrame {

    /**
     * Creates new form FormGajiPegawai
     */
    public FormGajiPegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNama = new javax.swing.JLabel();
        cbGolongan = new javax.swing.JComboBox<>();
        lbGolongan = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        chkMenikah = new javax.swing.JCheckBox();
        lbJamKerja = new javax.swing.JLabel();
        txtJamKerja = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        lbGaji = new javax.swing.JLabel();
        lbTunjangan = new javax.swing.JLabel();
        lbHonor = new javax.swing.JLabel();
        lbTotalGaji = new javax.swing.JLabel();
        lbPajak = new javax.swing.JLabel();
        lbGajiBersih = new javax.swing.JLabel();
        txtGapok = new javax.swing.JTextField();
        txtTunjangan = new javax.swing.JTextField();
        txtHonor = new javax.swing.JTextField();
        txtTotalGaji = new javax.swing.JTextField();
        txtPajak = new javax.swing.JTextField();
        txtBersih = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNama.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNama.setText("Nama");

        cbGolongan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbGolongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gol", "1", "2", "3", "4" }));

        lbGolongan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbGolongan.setText("Golongan");

        lbStatus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbStatus.setText("Status");

        chkMenikah.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        chkMenikah.setText("Menikah");

        lbJamKerja.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbJamKerja.setText("Jam Kerja");

        txtJamKerja.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lbGaji.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbGaji.setText("Gaji pokok");

        lbTunjangan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTunjangan.setText("Tunjangan");

        lbHonor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbHonor.setText("Total Honor");

        lbTotalGaji.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTotalGaji.setText("Total Gaji");

        lbPajak.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbPajak.setText("Pajak");

        lbGajiBersih.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbGajiBersih.setText("Gaji Bersih");

        txtGapok.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtGapok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGapokActionPerformed(evt);
            }
        });

        txtTunjangan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtHonor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtTotalGaji.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtPajak.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtBersih.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGolongan)
                                    .addComponent(lbStatus)
                                    .addComponent(lbJamKerja)
                                    .addComponent(lbNama))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(txtJamKerja)
                                    .addComponent(cbGolongan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkMenikah, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(btnHitung)))
                        .addGap(157, 157, 157))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)
                        .addGap(140, 140, 140)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGaji)
                    .addComponent(lbTunjangan)
                    .addComponent(lbHonor)
                    .addComponent(lbTotalGaji)
                    .addComponent(lbPajak)
                    .addComponent(lbGajiBersih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGapok)
                    .addComponent(txtTunjangan)
                    .addComponent(txtHonor)
                    .addComponent(txtTotalGaji, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtPajak)
                    .addComponent(txtBersih))
                .addGap(442, 442, 442))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNama)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbGaji)
                        .addComponent(txtGapok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGolongan)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTunjangan)
                        .addComponent(txtTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkMenikah)
                        .addComponent(lbHonor)
                        .addComponent(txtHonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJamKerja)
                    .addComponent(txtJamKerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalGaji)
                    .addComponent(txtTotalGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPajak)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGajiBersih)
                            .addComponent(txtBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnKeluar))))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGapokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGapokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGapokActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    try {
    int golongan = cbGolongan.getSelectedIndex();
    int jamKerja = Integer.parseInt(txtJamKerja.getText()); 
    
    double gapok = 0;
    double tunjangan = 0;
    
    switch(golongan) {
        case 1: gapok = 1000000; break; // Golongan 1
        case 2: gapok = 2000000; break; // Golongan 2
        case 3: gapok = 3000000; break; // Golongan 3
        case 4: gapok = 4000000; break; // Golongan 4
        default:
            JOptionPane.showMessageDialog(this, "Pilih golongan terlebih dahulu!");
            return; 
    }
    
    if (chkMenikah.isSelected()) {
        tunjangan = 500000;
    } else {
        tunjangan = 0;
    }
    
    double honor = jamKerja * 25000;
    double totalGaji = gapok + tunjangan + honor;
    
    double pajak = totalGaji * 0.025; 
    
    double gajiBersih = totalGaji - pajak;
    
    txtGapok.setText(Double.toString(gapok));
    txtTunjangan.setText(Double.toString(tunjangan));
    txtHonor.setText(Double.toString(honor));
    txtTotalGaji.setText(Double.toString(totalGaji));
    txtPajak.setText(Double.toString(pajak));
    txtBersih.setText(Double.toString(gajiBersih));

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Jam kerja harus diisi dengan angka bulat!");
    txtJamKerja.setText("");
    txtJamKerja.requestFocus();
}
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
    txtJamKerja.setText("");

    cbGolongan.setSelectedIndex(0); 
    chkMenikah.setSelected(false);  

    txtGapok.setText("");
    txtTunjangan.setText("");
    txtHonor.setText("");
    txtTotalGaji.setText("");
    txtPajak.setText("");
    txtBersih.setText("");

    txtNama.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, "Yakin mau menutup aplikasi penggajian?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
if (pilihan == JOptionPane.YES_OPTION) {
    System.exit(0);
}
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGajiPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbGolongan;
    private javax.swing.JCheckBox chkMenikah;
    private javax.swing.JLabel lbGaji;
    private javax.swing.JLabel lbGajiBersih;
    private javax.swing.JLabel lbGolongan;
    private javax.swing.JLabel lbHonor;
    private javax.swing.JLabel lbJamKerja;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbPajak;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTotalGaji;
    private javax.swing.JLabel lbTunjangan;
    private javax.swing.JTextField txtBersih;
    private javax.swing.JTextField txtGapok;
    private javax.swing.JTextField txtHonor;
    private javax.swing.JTextField txtJamKerja;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtTotalGaji;
    private javax.swing.JTextField txtTunjangan;
    // End of variables declaration//GEN-END:variables
}
